# Generated by Django 3.2.6 on 2022-05-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_homework'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Homework', 'verbose_name_plural': 'Homeworks'},
        ),
    ]
